### ISSUE TITLE
ds213 compatibility

### ISSUE THREAD

**Issue by patrickelectric** [gabonator/LA104#5]

**Comment by gabonator** [comment]
in progress

**Comment by gabonator** [comment]
![compatibility](https://github.com/gabonator/LA104/raw/master/resources/ladsall.jpg)

The operating system was ported to all devices I own (DS203 with hardware revision 2.60, DS213 and LA104). Currently I am working on simple oscilloscope and signal generator applications for DS203. Unfortunately, the DS213 has requires firmware update from the manufacturer, because the FPGA code has some issues with analog trigger

**Comment by blchinezu** [comment]
It it possible that the FPGA issues could be solved by the FW update released on 12th of March?
http://minidso.com/forum.php?mod=viewthread&tid=3357&extra=page%3D1

I'm actually eager to try your OS. I wonder, can DS213 decently work as a Logic Analyzer or it's better to buy the LA104 too?
